# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
if [[ -n "$PS1" ]]; then
    export BASH_HOME=~/.bash.d
    export EDITOR='vim'
    export IMAGE_VIEWER='gthumb'
    export BASH_THEME='equator'
    export TERM="xterm-256color"
    export MAD_PATH=$HOME/.mad
    export PATH=$HOME/.local/bin:$PATH

    # Pythons!
    export IPYTHONDIR=$HOME/.ipython
    export WORKON_HOME=$HOME/.virtualenv

    if [[ -s $HOME/.pyenv/bin/pyenv ]]; then
        export PATH=$PATH:$HOME/.pyenv/bin
        eval "$(pyenv init -)"
        pyenv virtualenvwrapper >&/dev/null
    fi

    # Erlang/OTPs!
    if [[ -s $HOME/.erlenv/bin/erlenv ]]; then
        export PATH=$PATH:$HOME/.erlenv/bin
        eval "$(erlenv init -)"
    fi

    # Go
    if [[ -s $HOME/.goenv/bin/goenv ]]; then
        export PATH=$PATH:$HOME/.goenv/bin
        eval "$(goenv init -)"
    fi

    if [[ -s $HOME/.genma/genma.sh ]]; then
        source $HOME/.genma/genma.sh
    fi

    # NodeJS
    if [[ -s $HOME/.nodenv/bin/nodenv ]]; then
        export PATH=$PATH:$HOME/.nodenv/bin
        eval "$(nodenv init -)"
    fi

    # Rust
    if [[ -s $HOME/.rsenv/bin/rsenv ]]; then
        export PATH=$PATH:$HOME/.rsenv/bin
        eval "$(rsenv init -)"
    fi

    # Ruby!
    if [[ -s $HOME/.rbenv/bin/rbenv ]]; then
        export PATH=$PATH:$HOME/.rbenv/bin
        eval "$(rbenv init -)"
    fi

    source $BASH_HOME/init.sh
fi
